### ISSUE TITLE
Issue in Makefile

### ISSUE THREAD

**Issue by smoke91** [FrontEndART/SonarQube-plug-in#1]
Module "sourcemeter-analyzer-base" should be build before "sonarqube-gui-plugin" because it's
one of gui-plugin dependency.

**Comment by pille5** [comment]
@smoke91, thanks for the bug report. We noticed this bug too and will be fixed in the newer version.

**Comment by pille5** [comment]
@smoke91, the new version is published. Please let me know if you have any problem with building the current master.
