### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by marcellorvalle** [FrontEndART/SonarQube-plug-in#2]
I am trying to build the project on my machine (Windows 7 + gnuWin Make) and after the downloading a lot of dependencies I receive the following errors:

> (...)
> [INFO] ------------------------------------------------------------------------
[INFO] Building SourceMeter base analyzer 8.0
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/com/sourcemeter/sonar-sourcemeter-core-plugin/8.0/sonar-sourcemeter-core-plugin-8.0.pom
[WARNING] The POM for com.sourcemeter:sonar-sourcemeter-core-plugin:jar:8.0 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/sourcemeter/sonar-sourcemeter-core-plugin/8.0/sonar-sourcemeter-core-plugin-8.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.360 s
[INFO] Finished at: 2016-02-09T02:20:38-02:00
[INFO] Final Memory: 10M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sonar-sourcemeter-analyzer-base: Could not resolve dependencies for project com.sourcemeter:sonar-sourcemeter-analyzer-base:jar:8.0: Could not find artifact com.sourcemeter:sonar-sourcemeter-core-plugin:jar:8.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
make: *** [sourcemeter-analyzer-base] Error 1

I have very limited knowledge about Maven and for me it seemed it could not find the remote repository. 

Maybe a little bit off-topic. I just need to get those files:

>sonar-sourcemeter-gui-plugin-8.0.jar
>sonar-sourcemeter-core-plugin-8.0.jar
>sonar-sourcemeter-analyzer-java-plugin-8.0.jar

Can I find it compiled somewhere?

Thanks!

**Comment by marcellorvalle** [comment]
It seems "SourceMeter base analyzer" needs to be built after "Sourcemeter core" and this is the reason maven was trying to fetch the core from the repository. 

I solved my problem changing the following line at Makefile:

>sonarqube-core-plugin: install-dependencies sourcemeter-analyzer-base

to

>sonarqube-core-plugin: install-dependencies

Tks!

**Comment by pille5** [comment]
@marcellorvalle, thanks for the bug report. You can find the compiled plugins under the release section: https://github.com/FrontEndART/SonarQube-plug-in/releases
I pushed a fix for the Makefile, so the current master should be able to build now.
