### ISSUE TITLE
Cannot start SonarQube 5.4

### ISSUE THREAD

**Issue by ericLemanissier** [FrontEndART/SonarQube-plug-in#3]
I installed the following jar files in extensions/plugins:
sonar-sourcemeter-gui-plugin-8.0.jar
sonar-sourcemeter-core-plugin-8.0.jar
sonar-sourcemeter-analyzer-cpp-plugin-8.0.jar

When restarting SonarQube 5.4, I get this error :

> ERROR web[jruby.rack] initialization failed                                                                                      
> org.jruby.rack.RackInitializationException: uninitialized constant SourcemeterDuplicationsController::SourceHelper                                   
>         from /opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:131:in `const_missing'                     
>         from /opt/sonarqube/temp/ror/SourceMeterGUI/app/controllers/sourcemeter_duplications_controller.rb:21:in `SourcemeterDuplicationsController' 
>         from /opt/sonarqube/temp/ror/SourceMeterGUI/app/controllers/sourcemeter_duplications_controller.rb:20:in `(root)'                            
>         from org/jruby/RubyKernel.java:1075:in `require'                                                                                             
>         from jar:file:/opt/sonarqube/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55: in `require'                                                                                                                                         
>         from jar:file:/opt/sonarqube/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53: in `require'                                                                                                                                         
>         from /opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:184:in `require'                           
>         from /opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:291:in `require_or_load'                   
>         from /opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:250:in `depend_on'                         
>         from /opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:162:in `require_dependency'                
>         from /opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:1:in `(root)'                                                      
>         from org/jruby/RubyArray.java:1613:in `each'                                                                                                 
>         from /opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:414:in `load_application_classes'                                  
>         from org/jruby/RubyArray.java:1613:in `each'                                                                                                 
>         from /opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:413:in `load_application_classes'                                  
>         from /opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:411:in `load_application_classes'                                  
>         from org/jruby/RubyKernel.java:2223:in `send'                                                                                                
>         from /opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:197:in `process'                                                   
>         from /opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:113:in `run'                                                       
>         from org/jruby/RubyKernel.java:1094:in `load'                                                                                                
>         from /opt/sonarqube/web/WEB-INF/config/environment.rb:86:in `(root)'                                                                           
>         from file:/opt/sonarqube/lib/server/jruby-rack-1.1.13.2.jar!/jruby/rack/rails/environment2.rb:1:in `(root)'                                  
>         from file:/opt/sonarqube/lib/server/jruby-rack-1.1.13.2.jar!/jruby/rack/rails/environment2.rb:25:in `load_environment'                       
>                                                                                                                                                      
>         at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29) ~[jruby-rack-1.1.13.2.jar:na]                        
>         at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:98) ~[jruby-rack-1.1.13.2.jar:na]                
>         at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50) ~[jruby-rack-1.1.13.2.jar:na]            
>         at org.sonar.server.platform.RubyRailsContextListener.contextInitialized(RubyRailsContextListener.java:35) [sonar-server-5.4.jar:na]         
>         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.30.jar:8.0.30]                   
>         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.30.jar:8.0.30]                   
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]                                
>         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]                     
>         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]                     
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45-internal]                                                           
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45-internal]                                    
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45-internal]                                    
>         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]                                                                              
> Caused by: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant SourcemeterDuplicationsController::SourceHelper                   
>         at RUBY.const_missing(/opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:131) ~[na:na]             
>         at RUBY.SourcemeterDuplicationsController(/opt/sonarqube/temp/ror/SourceMeterGUI/app/controllers/sourcemeter_duplications_controller.rb:21) ~[na:na]                                                                                                                         
>         at RUBY.(root)(/opt/sonarqube/temp/ror/SourceMeterGUI/app/controllers/sourcemeter_duplications_controller.rb:20) ~[na:na]                    
>         at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1075) ~[jruby-complete-1.7.9.jar:na]                                               
>         at Kernel.require(jar:file:/opt/sonarqube/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55) ~[na:na]                                                                                                                               
>         at Kernel.require(jar:file:/opt/sonarqube/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53) ~[na:na]                                                                                                                               
>         at ActiveSupport::Dependencies::Loadable.require(/opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:184) ~[na:na]                                                                                                                                       
>         at ActiveSupport::Dependencies.require_or_load(/opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:291) ~[na:na]                                                                                                                                         
>         at ActiveSupport::Dependencies.depend_on(/opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:250) ~[na:na]                                                                                                                                               
>         at ActiveSupport::Dependencies::Loadable.require_dependency(/opt/sonarqube/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:162) ~[na:na]                                                                                                                            
>         at RUBY.(root)(/opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:1) ~[na:na]                                              
>         at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613) ~[jruby-complete-1.7.9.jar:na]                                                    
>         at RUBY.load_application_classes(/opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:414) ~[na:na]                          
>         at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613) ~[jruby-complete-1.7.9.jar:na]                                                    
>         at RUBY.load_application_classes(/opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:413) ~[na:na]                          
>         at RUBY.load_application_classes(/opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:411) ~[na:na]                          
>         at org.jruby.RubyKernel.send(org/jruby/RubyKernel.java:2223) ~[jruby-complete-1.7.9.jar:na]                                                  
>         at RUBY.process(/opt/sonarqube/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:197) ~[na:na]

**Comment by pille5** [comment]
> The plug-in is compatible with the latest LTS (long term support) version 4.5 of the SONARQUBE™ platform, which can be obtained from its website. (This version of the plug-in was successfully tested with versions 4.4, and 4.5.6.)

@ericLemanissier, the plugin does not support the 5.X version of SonarQube server. You have to install SQ 4.5.x is you want to use the plugin. https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip

**Comment by ericLemanissier** [comment]
Right, sorry I missed that part !
