### ISSUE TITLE
execution failure for cpp project

### ISSUE THREAD

**Issue by ericLemanissier** [FrontEndART/SonarQube-plug-in#4]
Sourcemeter plugin always fails to execute on our CPP project. We are using sonarQube lts (4.5.6) , sourcemeter plugin 8.0 and sourcemeter 8.0.0

> INFO  -     Running SourceMeter toolchain...
> ERROR - SourceMeter toolchain could not be executed properly. Please check the log file for more information: /....../.sonar/sourcemeter.log
> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 9:09.382s
> INFO: Final Memory: 15M/584M
> INFO: ------------------------------------------------------------------------
> ERROR: Error during SonarQube Scanner execution
> org.sonar.api.utils.SonarException
> 	at com.sourcemeter.analyzer.base.batch.SourceMeterInitializer.runSourceMeter(SourceMeterInitializer.java:240)
> 	at com.sourcemeter.analyzer.cpp.batch.SourceMeterCppInitializer.execute(SourceMeterCppInitializer.java:104)
> 	at org.sonar.batch.phases.InitializersExecutor.execute(InitializersExecutor.java:69)
> 	at org.sonar.batch.phases.PhaseExecutor.executeInitializersPhase(PhaseExecutor.java:163)
> 	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:107)
> 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194)
> 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
> 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
> 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233)
> 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228)
> 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221)
> 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
> 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
> 	at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64)
> 	at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51)
> 	at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125)
> 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
> 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
> 	at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173)
> 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
> 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
> 	at org.sonar.runner.batch.BatchIsolatedLauncher.executeOldVersion(BatchIsolatedLauncher.java:86)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
> 	at com.sun.proxy.$Proxy0.executeOldVersion(Unknown Source)
> 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:283)
> 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
> 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
> 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:133)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:82)
> 	at org.sonarsource.scanner.cli.Main.main(Main.java:66)

.sonar/sourcemeter.log :

> SourceMeterCPP 8.0.0 (build 8717#44905  Linux64) - (C) 2001-2016 FrontEndART Ltd.
> Executing tasks. (Multithread:8)
>   [2016-04-02 14:30:34] Starting task: CleanResultsTask
>   [2016-04-02 14:30:34] Task ended: CleanResultsTask Result:OK
>   [2016-04-02 14:30:34] Starting task: WrapperTask
>   [2016-04-02 14:39:10] Task ended: WrapperTask Result:OK
>   [2016-04-02 14:39:10] Starting task: LinkStaticLibsTask
>   [2016-04-02 14:39:10] Task ended: LinkStaticLibsTask Result:OK
>   [2016-04-02 14:39:10] Starting task: RemoveWrapperBinsTask
>   [2016-04-02 14:39:10] Starting task: Can2limTask
>   [2016-04-02 14:39:10] Task ended: RemoveWrapperBinsTask Result:OK
>   [2016-04-02 14:39:10] Task ended: Can2limTask Result:critical error 
> Failed!

and result/project/cpp/2016-04-02-14-30-34/sourcemeter/log/Can2limTask.log

> [2016-04-02 14:39:10] Start:Can2limTask
> CAN2Lim 8.0.0 (build 8717#44905  Linux64) - (C) 2001-2016 FrontEndART Ltd.
> ERROR: No input file!
> Bad command line!
> 
> 
>   Usage:
> 
>     CAN2Lim [options]  input file(s)
>     
>     
>   Options:
>     
> 
>   -ilist:listfile
>     List file containing input filenames
> 
>   -out:outputfile
>     Output file
> 
>   -pathlower
>     Paths are converted to lower case for writting out
> 
>   -dLIMML
>     Create LIMML dump
> 
>   -dGRAPHML
>     Dump graphml to lim
> 
>   -scc
>     The conversion builds strongly connected components, too
> 
>   -novariants
>     No variants are built.
> 
>   -?
>   /?
>   -help
>     Displays the list of command line options
> 
>   -ml:number
>     Sets the message level of the program
>     0 (silent)  does not write any message
>     1 (error)   writes out error messages only
>     2 (warning) writes out error and warning messages
>     3 (normal)  writes out information about execution of the program
>     
> 
>   -ver
>     Displays the version information
> 
> EXCEPTION:src/Task.cpp:1216:ERROR: Execution failure! Exit:3
> 
> [2016-04-02 14:39:10] End:Can2limTask Result:critical error 

result/project/cpp/2016-04-02-14-30-34/sourcemeter/log/WrapperTask.log shows that the build itself happens flawlessly

**Comment by pille5** [comment]
Please run in debug mode at first (`sonar-runner -X`) and search for "`Calling SourceMeter toolchain:`" in the log of sonar-runner (stdout by default).

1. Try to run the toolchain command with only the mandatory parameters. If SM toolchain fails, then this is not a plugin error, so please contact the FrontEndART support at https://support.frontendart.com/portal/home and send your `result/project/cpp/2016-04-02-14-30-34/sourcemeter/log` folder if you can.
2. Otherwise the `-externalSoftFilter=/.../.sonar/softFilterFile` could be wrong. Please check that file too. (You can find the description of it's format in the SM users guide) This file is generated by the plugin, so if it is wrong, then we need to fix it here.
3. Don't forget to avoid the usage of symbolic links in your path. That can mess up the analysis.

**Comment by ericLemanissier** [comment]
Thanks for your answer. The softFilterFile looks suspicious to me.
The first line is `-.*` which seems ok, but all the other lines have the format 
`+\Q/actual/path/to/source/file\E` I wonder why are these `\Q` and `\E` present.

**Comment by pille5** [comment]
\Q and \E are for escaping RegExp special characters. SM expects RegExp patterns in the filter file. For example if you have path that contains a dot, then it will match on multiple paths. ex.:
`+my.folder` will match on `my1folder, my2folder, my.folder, myzfolder, ...etc`
`+\Qmy.folder\E will match only on `my.folder` (same as `+my\.folder`)

Does this mean that the analysis run fine without the filter file and `<project_name>.graph` file is created in the results directory?

**Comment by ericLemanissier** [comment]
Unfortunately I ran the toolchain command manually with parameters -resultsDir -projectName and -buildScript, and I got the exact same error, and I no graph file in the results directory, so it seems the problem lies in sourcemeter, not the plugin.

**Comment by ericLemanissier** [comment]
In the end, the problem is not a plugin error, but a Sourcemeter error. This CAN2Lim failure happens if there is no linker step in the build script, or if the link operation fails.
