### ISSUE TITLE
sonarqube's web context  set to /sonar , sourcemeter appears 404

### ISSUE THREAD

**Issue by huangliangyun** [FrontEndART/SonarQube-plug-in#46]
at sonaqube 7.9，SM 9.1，we set  'sonar.web.context=/sonar‘  for sonarqube， and the page of sourcemeter can't access.

the error is " https:168.192.52.12:9000/static/SourceMeterGUI/globals.js net::ERR_ABORTED " 404

**Comment by pille5** [comment]
@huangliangyun thank you for reporting this. #47 should have fixed this issue. A new release version will come soon, but you can build the current muster in the meantime. Please let us know if this or other issue still exists.
