### ISSUE TITLE
Accessing the filesystem before the Sensor phase is not supported.

### ISSUE THREAD

**Issue by jahnf** [FrontEndART/SonarQube-plug-in#5]
Hello, thank you for the plugin.
Is it possible to update the plugin for newer SonarQube versions like 6.0?
I get the following error when runing the sonar-scanner:

```
ERROR: Error during SonarQube Scanner execution
ERROR: Accessing the filesystem before the Sensor phase is not supported. Please update your plugin.
```

**Comment by pille5** [comment]
@jahnf, IMHO it is possible, but definetly not trivial. Unfortunalty I'm not familiar with the lastest SQ API, so not sure what tasks should be done to complete the update. One of the know issues is that accessing the filesystem before the sensor start. To fix this, you should move the toolchain run from the initiliziation phase to the sensor phase. Although you can access the filesystem in the sensor phase, I don't know you can manipulate it or it is only readable.

**Comment by ferencr** [comment]
The plug-in is now compatible with the latest LTS version 6.7 of the SonarQube platform.
