### ISSUE TITLE
Error of analyzing the python file using fastapi library

### ISSUE THREAD

**Issue by LeeJeffrey** [FrontEndART/SonarQube-plug-in#50]
Hi
    I am trying to use the SourceMeter plugin to analyze my python project. But I met one weird problem.
    My project use the fastapi(a popular python web framework) to provide some web-interface. some files are writed like below:

```{python}
from fastapi import FastAPI
from pydantic import BaseModel


app = FastAPI()


class UserIn(BaseModel):
    username: str
    password: str
    full_name: str = None


class UserOut(BaseModel):
    username: str
    full_name: str = None
```

   these codes are using the BaseModel class of the pydantic lib. the pycharm ide shows no error, and it can work correctly
   When the sonar-scanner scan the above files, it always report error or show a popup window said the PANTask.exe has stoped.
   So I try to find out why. 
   I delete the lines contains "=". Just leave the "key: value" sytle lines . The scanner failed as the same
   Then I delete the lines without "=" , Just leave the "key: value = something" lines. The scanner works fine.
   I did these tries many times. So I'm pretty sure that there are some trouble when source-meter handling the "key: value" lines.

  The source-meter logs shows:
```
Integrated 3rd party tool(s): SonarQube
Warning: Failed to retrieve version of Pylint. The Pylint checker will not be executed.
Executing tasks. (Multithread:8)
  [2021-03-07 23:53:41] Starting task:          PANTask
  [2021-03-07 23:53:41] Starting task:          CleanResultsTask
  [2021-03-07 23:53:41] Task ended (+00:00:00): CleanResultsTask               Result:OK
  [2021-03-07 23:54:17] Task ended (+00:00:36): PANTask                        Result:critical error 
EXCEPTION:Task.cpp:151:ERROR: Execution failure! Exit:-1073741819


Failed!
null
```  

   I have no idea the reason. please tell me how solve this problem.

**Comment by karanikiotis** [comment]
I have the exact same problem trying to analyze some python projects. Any idea?
