### ISSUE TITLE
The duplication is not shown at the snoarqube dash board

### ISSUE THREAD

**Issue by swchen44** [FrontEndART/SonarQube-plug-in#7]
When using the sourcemter C/C++,
the 2 type clone detection result is not shown at dsah borad.

Is there any plan to support it ?

**Comment by ferencr** [comment]
The default dashboard of SonarQube cannot be overwritten, its API does not allow it. You can find the clones on the SourceMeter dashboard: Go to your project and select the "More / SourceMeter Dashboard" menu. You will find the clones at the bottom of the page.
